### ISSUE TITLE
Rambox Javascript Error

### ISSUE THREAD

**Issue by Foggalong** [bilelmoussaoui/Hardcode-Tray#401] opened 2017-07-05 15:37 UTC
### Specifications
- Hardcode-Tray version : 3.9
- Distribution : Ubuntu 17.04
- Gtk version : 3.22
- Inkscape version : 0.92.1
- Cairo version : 1.0.20
- Sni-qt version: 0.2.7
- Application name :  Rambox
- Application version : ``

### Expected behavior and actual behavior
Expect Rambox to open with a themed tray icon. Instead an error window titled "A JavaScript error occurred in the main process" appears. Upon closing it Rambox launches but without a place in the tray at all. The content of the error message is as follows:

```
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /opt/Rambox/resources/app.asar/resources/IconTray.png
    at Object.exports.create (/opt/Rambox/resources/app.asar/electron/tray.js:34:12)
    at createWindow (/opt/Rambox/resources/app.asar/electron/main.js:162:7)
    at App.<anonymous> (/opt/Rambox/resources/app.asar/electron/main.js:444:65)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

### Steps to reproduce the problem
1. Install Rambox 0.5.9
2. Fix with Hardcode-Tray
3. Upgrade to Rambox 0.5.10
4. Fix with Hardcode-Tray

I've not tested whether this also occurs with a clean install of Rambox 0.5.10

**Comment by bil-elmoussaoui** [comment] 2017-07-05 16:50
Hmm, this shouldn't cause any issue at all :o as the upgrade process will change the asar file (that contains the assets of the application). Let me debug this :)
If you can try reinstalling a fresh version of Rambox and see if this works that would be awesome, also if you can reproduce that on the other electron application

**Comment by bil-elmoussaoui** [comment] 2017-07-05 17:02
+ Can you paste the latest log from /tmp/Hardcode-tray?

**Comment by Foggalong** [comment] 2017-07-06 14:15
I'm not somewhere I can VM stuff at the moment (in the process of moving house) so won't be able to sorry :( weirdly, applying Hardcode-Tray again seems to have fixed it so not sure what's going on there

**Comment by bil-elmoussaoui** [comment] 2017-07-06 15:47
I will try to reproduce this :) Good luck with that !

**Comment by bil-elmoussaoui** [comment] 2017-07-18 13:46
I couldn't reproduce this issue :(

**Comment by Foggalong** [comment] 2017-07-20 12:15
I wouldn't worry about it to be honest. It fixed itself almost immediately so whatever it is is going to be difficult to make happen again. I'd say close the issue and just remember it for if anything similar happens in future

**Comment by bil-elmoussaoui** [comment] 2017-07-20 12:18
Alright, makes sense. If you ever had this issue again, please don't forget to keep a copy of the log files (`/tmp/Hardcode-Tray`)

**Comment by Foggalong** [comment] 2017-09-07 11:42
@bil-elmoussaoui This happened again with the update to the latest version and I managed to snag the log file this time
```
[DEBUG] 2017-09-07 12:39:50 DE not detected.
[DEBUG] 2017-09-07 12:39:50 Config file: Not found.
[DEBUG] 2017-09-07 12:39:50 Arguments/Icon Size: None
[DEBUG] 2017-09-07 12:39:50 System/Icon Size: 22
[DEBUG] 2017-09-07 12:39:50 System/Theme: Numix-Circle
[DEBUG] 2017-09-07 12:39:50 Arguments/Conversion Tool: None
[DEBUG] 2017-09-07 12:39:50 Config/Conversion Tool: None
[DEBUG] 2017-09-07 12:39:50 SVG Factory: Failed RSVGConvert
[DEBUG] 2017-09-07 12:39:50 SVG Factory: Failed SVGExport
[DEBUG] 2017-09-07 12:39:50 SVG Factory: Import ImageMagick
[DEBUG] 2017-09-07 12:39:51 Path with condition: dropbox_callback {userhome}/.dropbox-dist/{dropbox}/images/hicolor/16x16/status/
[DEBUG] 2017-09-07 12:39:51 Path with condition: hangouts_callback /home/josh/.config/chromium/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-09-07 12:39:51 Path with condition: hangouts_callback /home/josh/.config/google-chrome/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-09-07 12:39:51 Path with condition: hangouts_callback /home/josh/.config/google-chrome-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-09-07 12:39:51 Path with condition: hangouts_callback /home/josh/.config/google-chrome-unstable/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-09-07 12:39:51 Path with condition: hangouts_callback /home/josh/.config/vivaldi/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-09-07 12:39:51 Path with condition: hangouts_callback /home/josh/.config/vivaldi-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-09-07 12:39:51 Path with condition: hangouts_callback /home/josh/.config/vivaldi-snapshot/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-09-07 12:39:51 Config/Backup Ignore: False
[DEBUG] 2017-09-07 12:39:51 Create new backup folder for Rambox
[DEBUG] 2017-09-07 12:39:51 Creating directory: /home/josh/.config/Hardcode-Tray/Rambox/07-09-2017_12-39-51/
[DEBUG] 2017-09-07 12:39:51 Executing command: convert -background none -resize 22x22 /usr/share/icons/Numix/22/status/rambox-notification.svg /tmp/tmpt68tk737
[DEBUG] 2017-09-07 12:39:52 Backup file: /tmp/files|resources|files|IconTrayUnread@4x.png to: /home/josh/.config/Hardcode-Tray/Rambox/07-09-2017_12-39-51/files|resources|files|IconTrayUnread@4x.png
[DEBUG] 2017-09-07 12:39:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Numix/22/status/rambox-indicator.svg /tmp/tmpv69i2qpl
[DEBUG] 2017-09-07 12:39:52 Backup file: /tmp/files|resources|files|IconTray@4x.png to: /home/josh/.config/Hardcode-Tray/Rambox/07-09-2017_12-39-51/files|resources|files|IconTray@4x.png
[DEBUG] 2017-09-07 12:39:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Numix/22/status/rambox-notification.svg /tmp/tmpedrar7bl
[DEBUG] 2017-09-07 12:39:52 Backup file: /tmp/files|resources|files|IconTrayUnread@2x.png to: /home/josh/.config/Hardcode-Tray/Rambox/07-09-2017_12-39-51/files|resources|files|IconTrayUnread@2x.png
[DEBUG] 2017-09-07 12:39:52 Executing command: convert -background none -resize 22x22 /usr/share/icons/Numix/22/status/rambox-indicator.svg /tmp/tmpfkllbh54
[DEBUG] 2017-09-07 12:39:53 Backup file: /tmp/files|resources|files|IconTray.png to: /home/josh/.config/Hardcode-Tray/Rambox/07-09-2017_12-39-51/files|resources|files|IconTray.png
[DEBUG] 2017-09-07 12:39:53 Executing command: convert -background none -resize 22x22 /usr/share/icons/Numix/22/status/rambox-indicator.svg /tmp/tmptm0wfjej
[DEBUG] 2017-09-07 12:39:53 Backup file: /tmp/files|resources|files|IconTray@2x.png to: /home/josh/.config/Hardcode-Tray/Rambox/07-09-2017_12-39-51/files|resources|files|IconTray@2x.png
[DEBUG] 2017-09-07 12:39:53 Executing command: convert -background none -resize 22x22 /usr/share/icons/Numix/22/status/rambox-notification.svg /tmp/tmpm_wbonkw
[DEBUG] 2017-09-07 12:39:53 Backup file: /tmp/files|resources|files|IconTrayUnread.png to: /home/josh/.config/Hardcode-Tray/Rambox/07-09-2017_12-39-51/files|resources|files|IconTrayUnread.png
[DEBUG] 2017-09-07 12:39:53 Create new backup folder for Steam
[DEBUG] 2017-09-07 12:39:53 Creating directory: /home/josh/.config/Hardcode-Tray/Steam/07-09-2017_12-39-53/
[DEBUG] 2017-09-07 12:39:53 Backup file: /usr/share/pixmaps/steam_tray_mono.png to: /home/josh/.config/Hardcode-Tray/Steam/07-09-2017_12-39-53/steam_tray_mono.png
[DEBUG] 2017-09-07 12:39:53 Executing command: convert -background none -resize 22x22 /usr/share/icons/Numix/22/status/steam_tray_mono.svg /usr/share/pixmaps/steam_tray_mono.png
```

**Comment by Foggalong** [comment] 2017-09-10 10:23
@bil-elmoussaoui This problem has persisted and doesn't seem to be going away this time. Could we get this issue reopened?

**Comment by bil-elmoussaoui** [comment] 2017-09-10 10:44
There's nothing on the asar file :( does this happens with any other electron app?

**Comment by Foggalong** [comment] 2017-09-10 10:47
I don't use any other electron apps which have tray icons :frowning_face:

**Comment by bil-elmoussaoui** [comment] 2017-09-10 10:58
Let me install Rambox and see how i can handle this

**Comment by Foggalong** [comment] 2017-09-10 11:09
As a note, the issue seems to be specifically to do with upgrading from one version to another. I've not had it appear in any other scenario.

**Comment by bil-elmoussaoui** [comment] 2017-12-18 23:11
I wasn't able to reproduce this at all :(
It seems that somehow the icons were corrupted on the asar file (the file used by electron to store assets and some js files)

**Comment by bil-elmoussaoui** [comment] 2018-01-22 10:57
I was able to reproduce this by using hardcode-tray without closing Rambox. And there's no simple way of us to detect if the application is running :/ I think we should just add a warning to ask the user to close all the applications before using Hardcode-Tray?

**Comment by Foggalong** [comment] 2018-01-23 09:17
Yeah, that would be good :+1:

**Comment by bilelmoussaoui** [comment] 2018-05-25 12:22
Already added the warning. Closing

**Closed by bilelmoussaoui** 2018-05-25 12:22 UTC
Labels: bug
