### ISSUE TITLE
Mattermost

### ISSUE THREAD

**Issue by rauldipeas** [bilelmoussaoui/Hardcode-Tray#704] opened 2021-08-28 02:58 UTC
![image](https://user-images.githubusercontent.com/12108031/131204171-4db643b0-11bd-4f98-8d39-32d3943256bf.png)

**Comment by rauldipeas** [comment] 2021-09-21 15:00
This needs an update, i'm trying to do it here, but no lucky...
```
{
    "name": "Mattermost",
    "app_path": [
        "/opt/Mattermost/",
        "/usr/lib/mattermost/"
    ],
    "icons_path": [
        "/opt/Mattermost/resources/",
        "/usr/lib/mattermost/resources/"
    ],
    "binary": "app.asar",
    "script": "electron",
    "icons": {
        "tray-light": {
            "original": "assets/linux/top_bar_light_16.png",
            "theme": "mattermost-tray"
        },
        "tray-light-unread": {
            "original": "assets/linux/top_bar_unread_light_16.png",
            "theme": "mattermost-unread"
        },
        "tray-light-mention": {
            "original": "assets/linux/top_bar_mention_light_16.png",
            "theme": "mattermost-mention"
        },
        "tray-light@2x": {
            "original": "assets/linux/top_bar_light_16@2x.png",
            "theme": "mattermost-tray"
        },
        "tray-light@2x-unread": {
            "original": "assets/linux/top_bar_unread_light_16@2x.png",
            "theme": "mattermost-unread"
        },
        "tray-light@2x-mention": {
            "original": "assets/linux/top_bar_mention_light_16@2x.png",
            "theme": "mattermost-mention"
        },
        "tray-dark": {
            "original": "assets/linux/top_bar_dark_16.png",
            "theme": "mattermost-tray"
        },
        "tray-dark-unread": {
            "original": "assets/linux/top_bar_unread_dark_16.png",
            "theme": "mattermost-unread"
        },
        "tray-dark-mention": {
            "original": "assets/linux/top_bar_mention_dark_16.png",
            "theme": "mattermost-mention"
        },
        "tray-dark@2x": {
            "original": "assets/linux/top_bar_dark_16@2x.png",
            "theme": "mattermost-tray"
        },
        "tray-dark@2x-unread": {
            "original": "assets/linux/top_bar_unread_dark_16@2x.png",
            "theme": "mattermost-unread"
        },
        "tray-dark@2x-mention": {
            "original": "assets/linux/top_bar_mention_dark_16@2x.png",
            "theme": "mattermost-mention"
        }
    }
}
```
```
 rauldipeas@IdeaPad-320  ~  sudo hardcode-tray --apply --only mattermost.electron
Welcome to Hardcode-Tray!
Hardcode-Tray replaces some icons on the binary files of some applications. 
Please close all the running applications before running Hardcode-Tray script.
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 24
Icon Theme: Luv
Conversion Tool: RSVGConvert
To Do: Mattermost.Electron
Applying now..


Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 121, in <module>
    App.execute()
  File "/usr/lib/python3.7/site-packages/HardcodeTray/app.py", line 120, in execute
    delta = app.do_action(action)
  File "/usr/lib/python3.7/site-packages/HardcodeTray/modules/applications/application.py", line 148, in do_action
    self.install()
  File "/usr/lib/python3.7/site-packages/HardcodeTray/decorators.py", line 58, in wrapper
    func(app)
  File "/usr/lib/python3.7/site-packages/HardcodeTray/modules/applications/application.py", line 96, in install
    self.execute(Action.APPLY)
  File "/usr/lib/python3.7/site-packages/HardcodeTray/modules/applications/helpers/binary.py", line 50, in execute
    self.install_icon(icon, icon_path)
  File "/usr/lib/python3.7/site-packages/HardcodeTray/modules/applications/electron.py", line 41, in install_icon
    self.set_icon(icon, icon_path, png_bytes, True)
  File "/usr/lib/python3.7/site-packages/HardcodeTray/modules/applications/electron.py", line 66, in set_icon
    asar.write(icon_to_replace, png_bytes)
  File "/usr/lib/python3.7/site-packages/HardcodeTray/modules/applications/helpers/asar.py", line 106, in write
    new_files = change_dict_vals(self._header, sizediff, offset0)
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in change_dict_vals
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in <dictcomp>
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in change_dict_vals
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in <dictcomp>
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in change_dict_vals
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in <dictcomp>
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in change_dict_vals
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in <dictcomp>
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in change_dict_vals
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in <dictcomp>
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in change_dict_vals
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in <dictcomp>
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in change_dict_vals
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in <dictcomp>
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in change_dict_vals
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in <dictcomp>
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in change_dict_vals
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 244, in <dictcomp>
    d2 = {k: change_dict_vals(v, sizediff, offset) for k, v in d.items()}
  File "/usr/lib/python3.7/site-packages/HardcodeTray/utils.py", line 245, in change_dict_vals
    if d2.get('offset') and int(d2.get('offset')) > offset:
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'
```

**Comment by rauldipeas** [comment] 2021-09-21 15:04
![image](https://user-images.githubusercontent.com/12108031/134196257-1c9feee2-7d46-4ec2-ac2c-e12de2cd0401.png)

**Comment by varlesh** [comment] 2021-09-22 00:06
Current release 4.7.2 and i'm not seen your icons on this location:
![Screenshot_20210922_040427](https://user-images.githubusercontent.com/8083855/134263232-9aa73ba2-084d-4486-9176-5a6dadb4fc63.png)

**Comment by varlesh** [comment] 2021-09-22 00:07
assets:
![Screenshot_20210922_040639](https://user-images.githubusercontent.com/8083855/134263323-a41d2d80-3192-441c-af2f-8ee88f3dd4c2.png)

**Comment by varlesh** [comment] 2021-09-22 00:10
ough, it's 5.0.0 RC

**Comment by rauldipeas** [comment] 2021-09-22 00:10
I'm on version 5.0.0-rc1-13336.

**Comment by varlesh** [comment] 2021-09-22 00:12
similar bug #646

**Comment by varlesh** [comment] 2021-09-22 00:14
downgrade to 4.7.2
i don't know how solve this

**Comment by rauldipeas** [comment] 2021-09-22 00:15
I'm fixed Gitify manually, with a script that replace files.

**Comment by varlesh** [comment] 2021-09-22 00:18
and #637 to

**Comment by rauldipeas** [comment] 2021-09-22 00:23
I'm fixing Gitify like this...
```
npx asar e /opt/Gitify/resources/app.asar app
rsvg-convert /usr/share/icons/Papirus/24x24/panel/gitify-tray-active.svg -o app/assets/images/tray-active.png 
rsvg-convert /usr/share/icons/Papirus/24x24@2x/panel/gitify-tray-active.svg -w 48 -o app/assets/images/tray-active@2x.png 
rsvg-convert /usr/share/icons/Papirus/24x24/panel/gitify-tray.svg -o app/assets/images/tray-idleTemplate.png 
rsvg-convert /usr/share/icons/Papirus/24x24@2x/panel/gitify-tray.svg -w 48 -o app/assets/images/tray-idleTemplate@2x.png
npx asar p app app.asar
sudo cp -rfv app.asar /opt/Gitify/resources/app.asar
```

**Comment by varlesh** [comment] 2021-09-22 00:50
@acarasimon96 Timothy you know python, maybe you can help solve this error?
I think [asar ](https://github.com/bilelmoussaoui/Hardcode-Tray/blob/master/HardcodeTray/modules/applications/helpers/asar.py) module don't get header bytes for right work on some electron-apps.
`TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'`

For test you can use this app. Extract archives and found **resources/app.asar** file.
This worked:
https://releases.mattermost.com/desktop/4.7.2/mattermost-desktop-4.7.2-linux-x64.tar.gz
This not worked:
https://releases.mattermost.com/desktop/5.0.0-rc1/mattermost-desktop-5.0.0-rc1-linux-x64.tar.gz

**Comment by acarasimon96** [comment] 2021-09-22 02:05
I just successfully ran Hardcode Tray Git version on the Mattermost desktop app, but I'm not getting a `TypeError` on my end. I'm not getting any useful hints either in the debug logs.

It appears that the tray icons in `app.asar` matches those shown in [this comment](https://github.com/bilelmoussaoui/Hardcode-Tray/issues/704#issuecomment-924077561) by the issue creator. If Hardcode Tray really did replace the icons as expected, the icons between light and dark variants in that same directory would be identical.

![image](https://user-images.githubusercontent.com/17580077/134271444-3eafcdc0-f17f-418f-8d6d-2b03185d9669.png)

For comparison, here are the icons from Papirus that were supposed to replace the above:

![image](https://user-images.githubusercontent.com/17580077/134271491-2a867e68-7594-4962-a30e-974f01164294.png)

I don't think this looks like an easy fix for me, but it's possible to get it done. This will take a couple days for me to find out the cause and implement a fix since I also have school, chores at home, and other interests to deal with. I apologize for any inconvenience that may arise out of my life situation.

Also, thank you for the unexpected ping, @varlesh. I'm thrilled to be able to help you out with  this issue!

**Comment by rauldipeas** [comment] 2021-09-22 02:12
I'm temporarily using this solution to fix tray icons on my `apt` repository.
https://gitlab.com/myawesomedistro/madrepo/-/blob/main/scripts/mkpkg/mattermost.sh

**Comment by varlesh** [comment] 2021-09-22 02:18
@acarasimon96 Thanks for your efforts... it's only your desire, I do not insist

**Comment by varlesh** [comment] 2021-09-22 02:20
>I just successfully ran Hardcode Tray Git version on Mattermost desktop 5.0.0-rc1, but I'm not getting a TypeError on my end. I'm not getting any useful hints either in the debug logs

for 5.0.0 RC need use [this config](https://github.com/bilelmoussaoui/Hardcode-Tray/issues/704#issuecomment-924074132)

**Comment by acarasimon96** [comment] 2021-09-22 02:26
Oh, I didn't realize to do that first. Now I'm getting the same exact error you got.

**Comment by acarasimon96** [comment] 2021-09-23 02:03
I was able to fix the crash, and it was a bit easier than I thought. It was caused by a directory that is literally called "offset" inside app.asar. I changed the code to where it makes sure that the value for "offset" is a string (that is, the real offset value of a file) before recalculating it. However, for some weird reason, I still couldn't get the script to replace the mention and unread icons. I would consider this issue solved once that new bug gets fixed and no other side effects come out of that.

**Comment by varlesh** [comment] 2021-09-23 02:35
@acarasimon96 glad to hear about success
On logs backup only 16px icons:
```
[DEBUG] 2021-09-23 06:22:43 Create new backup folder for Mattermost
[DEBUG] 2021-09-23 06:22:43 Creating directory: /home/alex/.config/Hardcode-Tray/Mattermost/2021-09-23 06:22:43/
[DEBUG] 2021-09-23 06:22:43 Executing command: rsvg-convert -f png -o /tmp/tmp9jdsnztd -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-tray.svg
[DEBUG] 2021-09-23 06:22:44 Backup file: /tmp/files|assets|files|linux|files|top_bar_light_16.png to: /home/alex/.config/Hardcode-Tray/Mattermost/2021-09-23 06:22:43/files|assets|files|linux|files|top_bar_light_16.png
[DEBUG] 2021-09-23 06:22:44 Executing command: rsvg-convert -f png -o /tmp/tmpx9blhr3j -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-unread.svg
[DEBUG] 2021-09-23 06:22:44 Executing command: rsvg-convert -f png -o /tmp/tmpylubzicr -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-mention.svg
[DEBUG] 2021-09-23 06:22:44 Executing command: rsvg-convert -f png -o /tmp/tmp3pcydgli -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-tray.svg
[DEBUG] 2021-09-23 06:22:44 Backup file: /tmp/files|assets|files|linux|files|top_bar_light_16@2x.png to: /home/alex/.config/Hardcode-Tray/Mattermost/2021-09-23 06:22:43/files|assets|files|linux|files|top_bar_light_16@2x.png
[DEBUG] 2021-09-23 06:22:44 Executing command: rsvg-convert -f png -o /tmp/tmphyomnemk -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-unread.svg
[DEBUG] 2021-09-23 06:22:44 Executing command: rsvg-convert -f png -o /tmp/tmpdc8i4nab -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-mention.svg
[DEBUG] 2021-09-23 06:22:44 Executing command: rsvg-convert -f png -o /tmp/tmpaq7hwufl -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-tray.svg
[DEBUG] 2021-09-23 06:22:44 Backup file: /tmp/files|assets|files|linux|files|top_bar_dark_16.png to: /home/alex/.config/Hardcode-Tray/Mattermost/2021-09-23 06:22:43/files|assets|files|linux|files|top_bar_dark_16.png
[DEBUG] 2021-09-23 06:22:44 Executing command: rsvg-convert -f png -o /tmp/tmp3wgx1tc2 -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-unread.svg
[DEBUG] 2021-09-23 06:22:44 Executing command: rsvg-convert -f png -o /tmp/tmp_i3kucko -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-mention.svg
[DEBUG] 2021-09-23 06:22:44 Executing command: rsvg-convert -f png -o /tmp/tmpxeukqnhp -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-tray.svg
[DEBUG] 2021-09-23 06:22:44 Backup file: /tmp/files|assets|files|linux|files|top_bar_dark_16@2x.png to: /home/alex/.config/Hardcode-Tray/Mattermost/2021-09-23 06:22:43/files|assets|files|linux|files|top_bar_dark_16@2x.png
[DEBUG] 2021-09-23 06:22:44 Executing command: rsvg-convert -f png -o /tmp/tmpwmyv1ufh -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-unread.svg
[DEBUG] 2021-09-23 06:22:44 Executing command: rsvg-convert -f png -o /tmp/tmptszjzw7e -w 22 -h 22 /usr/share/icons/Papirus-Dark/22x22/panel/mattermost-mention.svg
```

**Comment by varlesh** [comment] 2021-09-23 02:36
Other files not backuped
![Screenshot_20210923_063615](https://user-images.githubusercontent.com/8083855/134447112-1da5efe7-91b0-4231-8646-0bdcd394b9be.png)

**Comment by acarasimon96** [comment] 2021-09-23 02:39
> I still couldn't get the script to replace the mention and unread icons. I would consider this issue solved once that new bug gets fixed and no other side effects come out of that.

> On logs backup only 16px and 16@2x icons

It turns out that a few typos in [this comment with the modified `mattermost.electron.json`]() is what prevented the unread and mentioned tray icons from being replaced or backed up. I moved `mention` and `unread` after `light` or `dark` in the JSON, depending on the target filename, and it worked!

<details>
<summary>Here is the corrected `mattermost.electron.json` file</summary>

```json
{
    "name": "Mattermost",
    "app_path": [
        "/opt/Mattermost/",
        "/usr/lib/mattermost/"
    ],
    "icons_path": [
        "/opt/Mattermost/resources/",
        "/usr/lib/mattermost/resources/"
    ],
    "binary": "app.asar",
    "script": "electron",
    "icons": {
        "tray-light": {
            "original": "assets/linux/top_bar_light_16.png",
            "theme": "mattermost-tray"
        },
        "tray-light-unread": {
            "original": "assets/linux/top_bar_light_unread_16.png",
            "theme": "mattermost-unread"
        },
        "tray-light-mention": {
            "original": "assets/linux/top_bar_light_mention_16.png",
            "theme": "mattermost-mention"
        },
        "tray-light@2x": {
            "original": "assets/linux/top_bar_light_16@2x.png",
            "theme": "mattermost-tray"
        },
        "tray-light@2x-unread": {
            "original": "assets/linux/top_bar_light_unread_16@2x.png",
            "theme": "mattermost-unread"
        },
        "tray-light@2x-mention": {
            "original": "assets/linux/top_bar_light_mention_16@2x.png",
            "theme": "mattermost-mention"
        },
        "tray-dark": {
            "original": "assets/linux/top_bar_dark_16.png",
            "theme": "mattermost-tray"
        },
        "tray-dark-unread": {
            "original": "assets/linux/top_bar_dark_unread_16.png",
            "theme": "mattermost-unread"
        },
        "tray-dark-mention": {
            "original": "assets/linux/top_bar_dark_mention_16.png",
            "theme": "mattermost-mention"
        },
        "tray-dark@2x": {
            "original": "assets/linux/top_bar_dark_16@2x.png",
            "theme": "mattermost-tray"
        },
        "tray-dark@2x-unread": {
            "original": "assets/linux/top_bar_dark_unread_16@2x.png",
            "theme": "mattermost-unread"
        },
        "tray-dark@2x-mention": {
            "original": "assets/linux/top_bar_dark_mention_16@2x.png",
            "theme": "mattermost-mention"
        }
    }
}

```
</details>

And below is the final result with the icons properly replaced
![image](https://user-images.githubusercontent.com/17580077/134446854-1491cc7c-7148-42e8-a697-a2807a76b07b.png)

**Comment by varlesh** [comment] 2021-09-23 02:39
also i'm extract patched asar and selected files - it's Papirus files 100 %
![Screenshot_20210923_063810](https://user-images.githubusercontent.com/8083855/134447278-e9f8d89e-99be-4ca0-952e-596278f33651.png)

**Comment by varlesh** [comment] 2021-09-23 02:40
@acarasimon96 Congratulations, you are cool!!! :1st_place_medal: 
I can merge PR?

**Comment by acarasimon96** [comment] 2021-09-23 02:42
Sure, go ahead, but make sure you test the PR first on your system before merging. I'm glad I was able to help out. 😊

**Comment by varlesh** [comment] 2021-09-23 02:44
@acarasimon96 Big thx!!! I'm also test it with other problem apps Franz #637 & Gitify #646 and merged

**Comment by varlesh** [comment] 2021-09-23 02:45
> P.S. @rauldipeas, please remember to submit a new PR containing the new JSON file.

I'm doing this

**Comment by rauldipeas** [comment] 2021-09-23 02:49
Thank you so much @acarasimon96 and @varlesh, this fix help-me so much!

**Closed** 2021-09-23 02:55 UTC
Labels: bug, help wanted

**Comment by varlesh** [comment] 2021-09-23 02:59
Franz & Gitify fixed too!

**Comment by steakscience** [comment] 2022-05-02 10:56
I'm on Mattermost 5.0.4, and hardcode-tray doesn't detect it. Does it work for others?

**Comment by rauldipeas** [comment] 2022-05-02 11:00
![image](https://user-images.githubusercontent.com/12108031/166223955-44fc2bb3-41c4-4617-a6d7-41205e90e1ca.png)

**Comment by steakscience** [comment] 2022-05-02 12:07
@rauldipeas Interesting... I do have `app.asar` in `/usr/lib` (same as https://github.com/bilelmoussaoui/Hardcode-Tray/blob/38d5e52a965a105dfcdb7dffed60c4316c6e9fa1/data/database/mattermost.electron.json) but I don't know why it's not detecting.

It is detecting my apps just fine
