### ISSUE TITLE
Synergy not working

### ISSUE THREAD

**Issue by flops** [bilelmoussaoui/Hardcode-Tray#432] opened 2017-09-01 23:00 UTC
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `Arch`
- Gtk version : `3.22.19`
- Inkscape version : `0.92.2 5c3e80d, 2017-08-06` if installed
- Cairo version : `2.0.3` if installed
- Sni-qt version: `r.-1` if installed
- Application name :  `synergy`
- Application version : `1.8.8`

### Expected behavior and actual behavior
Papirus Icons theme got synergy panel icon, hardcode-tray detects it but icon not changed.

**Comment by bil-elmoussaoui** [comment] 2017-09-02 15:53
Synergy is a qt application. Either the application is moved to use qt5 which then will be a duplicate of #293. If not, the sni-qt doesn't work correctly on archlinux with Gnome. I myself use Archlinux, and i wasn't able to debug that :( Currently, i'm so busy. But once i have some free time i will improve the situation  (sni-qt is built using C++, and my C++ skills are not that good :( which makes it even harder to do)

**Comment by wa4557** [comment] 2017-09-17 16:26
For me synergy is fixed. Running version 1.8.8 and Numix icon theme

**Comment by bil-elmoussaoui** [comment] 2017-09-17 16:29
Yeah it works on any DE other than Gnome, it's a sni-qt issue...

**Comment by wa4557** [comment] 2017-09-17 16:37
This Qt programs are a pain in the ass...

**Comment by bil-elmoussaoui** [comment] 2017-09-17 16:40
Yeah... Too complicated for almost nothing, I don't use any Qt application, so working on sni-qt is really something I'm not willing to spend my time on anytime soon :/

**Comment by ceiphr** [comment] 2020-03-24 02:28
Any new updates on this issue and Gnome? I see Synergy has switched to qt5(#578).

**Comment by varlesh** [comment] 2021-09-23 03:59
icons on binary, open issue here: https://github.com/symless/synergy-core/issues
It's can be possible with `QIcon::fromTheme`

**Closed by varlesh** 2021-09-23 03:59 UTC
Labels: bug, help wanted
