### ISSUE TITLE
No PPA for Ubuntu 18.04 artful

### ISSUE THREAD

**Issue by georgelemental** [bilelmoussaoui/Hardcode-Tray#522] opened 2018-05-08 20:53 UTC
### Specifications
Distribution : `Ubuntu 18.04`

### Expected behavior and actual behavior
The Hardcode-Tray PPA contains no packages for Ubuntu 18.04, which breaks updates on that OS.

**Comment by bilelmoussaoui** [comment] 2018-05-16 07:33
Duplicate of #518

**Closed by bilelmoussaoui** 2018-05-16 07:33 UTC
